services:
  mongodb:
    image: mongo:6.0
    container_name: ourverse-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ourverse
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - ourverse-network

  app:
    build: .
    container_name: ourverse-app
    restart: unless-stopped
    ports:
      - "${DOCKER_APP_PORT:-3000}:${DOCKER_APP_PORT:-3000}"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - ourverse-network

  nginx:
    image: nginx:alpine
    container_name: ourverse-nginx
    restart: unless-stopped
    ports:
      - "${DOCKER_NGINX_HTTP_PORT:-80}:${DOCKER_NGINX_HTTP_PORT:-80}"
      - "${DOCKER_NGINX_HTTPS_PORT:-443}:${DOCKER_NGINX_HTTPS_PORT:-443}"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./uploads:/var/www/uploads:ro
    depends_on:
      - app
    networks:
      - ourverse-network

volumes:
  mongodb_data:

networks:
  ourverse-network:
    driver: bridge
