services:
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ourverse
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    # Railway会自动处理网络连接，无需手动配置

  app:
    build:
      context: ../backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=${PORT:-3000}
      # Railway会注入数据库URL等环境变量
      - MONGODB_URI=${MONGODB_URI}
    env_file:
      - ../.env
    volumes:
      - ../backend/uploads:/app/uploads
      - ../backend/logs:/app/logs
    depends_on:
      - mongodb
    # Railway会自动暴露端口，无需手动配置

volumes:
  mongodb_data:
    # Railway提供持久化存储，无需额外配置
