[build]
# 使用Docker构建
builder = "docker"
dockerfilePath = "../backend/Dockerfile"
context = "../backend"

[deploy]
# 部署配置
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# 环境变量（这些将在Railway控制台中设置）
# MONGODB_URI - Railway自动提供
# JWT_SECRET - 需要手动设置
# GITHUB_CLIENT_ID - 需要手动设置
# GITHUB_CLIENT_SECRET - 需要手动设置
# AMAP_WEB_API_KEY - 需要手动设置
# AMAP_REST_API_KEY - 需要手动设置
# AMAP_SECURITY_CODE - 需要手动设置

[services.mongodb]
# MongoDB服务配置
autoDeploy = true
healthcheckPath = "/"
healthcheckTimeout = 30

[services.app]
# 应用服务配置
autoDeploy = true
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# 域名配置（在Railway控制台设置）
# domains = ["your-app.railway.app"]
